# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160516_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='level',
            field=models.CharField(choices=[('UN', 'Unarian'), ('DE', 'Decenarian'), ('CE', 'Centenarian')], default='UN', max_length=2),
        ),
    ]
